### ISSUE TITLE
reinforcement_q_learning.ipynb代码测试问题

### ISSUE THREAD

**Issue by GuilinF** [qqiang00/reinforce#3]

**Comment by GuilinF** [comment]
您好，我在跑您代码reinforcement_q_learning.ipynb过程中，出现了如下的bug，但是我始终调试不通，如您解答，不胜感激。
D:\Anaconda3\lib\site-packages\gym\envs\registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Traceback (most recent call last):
  File "D:/Anaconda3code/强化学习-吴强/第六章的DQN/reinforcement_q_learning1.py", line 113, in <module>
    plt.imshow(get_screen().cpu().squeeze(0).permute(1, 2, 0).numpy(),
  File "D:/Anaconda3code/强化学习-吴强/第六章的DQN/reinforcement_q_learning1.py", line 88, in get_screen
    screen = env.render(mode='rgb_array').transpose(
  File "D:\Anaconda3\lib\site-packages\gym\envs\classic_control\cartpole.py", line 188, in render
    return self.viewer.render(return_rgb_array = mode=='rgb_array')
  File "D:\Anaconda3\lib\site-packages\gym\envs\classic_control\rendering.py", line 96, in render
    arr = np.fromstring(image_data.data, dtype=np.uint8, sep='')
AttributeError: 'ImageData' object has no attribute 'data'
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x00000000160EAC88>>
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\gym\envs\classic_control\rendering.py", line 143, in __del__
  File "D:\Anaconda3\lib\site-packages\gym\envs\classic_control\rendering.py", line 62, in close
  File "D:\Anaconda3\lib\site-packages\pyglet\window\win32\__init__.py", line 306, in close
  File "D:\Anaconda3\lib\site-packages\pyglet\window\__init__.py", line 834, in close
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by GuilinF** [comment]
D:\Anaconda3\lib\site-packages\gym\envs\registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Traceback (most recent call last):
  File "D:/Anaconda3code/强化学习-叶强/第六章的DQN/reinforcement_q_learning1.py", line 113, in <module>
    plt.imshow(get_screen().cpu().squeeze(0).permute(1, 2, 0).numpy(),
  File "D:/Anaconda3code/强化学习-叶强/第六章的DQN/reinforcement_q_learning1.py", line 88, in get_screen
    screen = env.render(mode='rgb_array').transpose(
  File "D:\Anaconda3\lib\site-packages\gym\envs\classic_control\cartpole.py", line 188, in render
    return self.viewer.render(return_rgb_array = mode=='rgb_array')
  File "D:\Anaconda3\lib\site-packages\gym\envs\classic_control\rendering.py", line 96, in render
    arr = np.fromstring(image_data.data, dtype=np.uint8, sep='')
AttributeError: 'ImageData' object has no attribute 'data'
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x00000000160D5CF8>>
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\gym\envs\classic_control\rendering.py", line 143, in __del__
  File "D:\Anaconda3\lib\site-packages\gym\envs\classic_control\rendering.py", line 62, in close
  File "D:\Anaconda3\lib\site-packages\pyglet\window\win32\__init__.py", line 306, in close
  File "D:\Anaconda3\lib\site-packages\pyglet\window\__init__.py", line 834, in close
ImportError: sys.meta_path is None, Python is likely shutting down
